name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: astral-sh/ruff-action@v3
      with:
        args: check --exit-zero --output-format=full --select=ALL --statistics
    - run: |
        values=(1 10 100 1000 10000 100000 1000000 10000000 0 -1)
        # Loop through each value and run the benchmark script
        for value in "${values[@]}"; do
          echo "time python src/nbody.py $value"
          time python src/nbody.py "$value"
          sleep 1  # Allow time to print its output
          echo "---------------------------"
        done
